name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: google-github-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.2'
          ndk-version: '23.2.8568313'
          cmake: '3.22.1'
          components: |
            platform-tools
            cmdline-tools
      - name: Accept Android SDK licenses
        run: yes | sdkmanager --licenses

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release \
          --dart-define=LOGIN=${{ secrets.LOGIN }} \
          --dart-define=PASSWORD=${{ secrets.PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
