name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  flutter-build:
    name: Flutter build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release \
          --dart-define=LOGIN=${{ secrets.LOGIN }} \
          --dart-define=PASSWORD=${{ secrets.PASSWORD }}
