name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      FLUTTER_VERSION: '3.29.3'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK & NDK
        uses: google-github-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: '33.0.2'
          ndk: '29.0.13113456'
          components: |
            platform-tools
            platforms;android-33

      - name: Flutter pub get
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release \
          --dart-define=LOGIN=${{ secrets.LOGIN }} \
          --dart-define=PASSWORD=${{ secrets.PASSWORD }}

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk
