name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'

    - name: Set up Android SDK
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: default
        arch: x86_64
        disable-animations: true
        script: echo "Android SDK is ready!"

    - name: Accept Android Licenses
      run: yes | sdkmanager --licenses

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release --dart-define=LOGIN=${{ secrets.LOGIN }} --dart-define=PASSWORD=${{ secrets.PASSWORD }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
